name: 'sandbox-container-action'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'docker.pkg.github.com/kondoumh/sandbox-container-action/sandbox-container-action:latest'
  args:
    - ${{ inputs.who-to-greet }}
