name: Docker Image CI

on:
  push:
    paths: 
      - Dockerfile
      - .github/workflows/dockerimage.yml

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build image and Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: docker.pkg.github.com/kondoumh/sandbox-container-action/sandbox-container-action
        username: kondoumh
        password: ${{ secrets.REGISTRY_TOKEN }}
        registry: docker.pkg.github.com
